<div class="row">
	<div class="col-md-6">    
        <div class="card mb-4">
        <?php
        $this->form->prepare();
        echo $this->form()->openTag($form);
        ?>
        	<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Update</b>
        		</div>
        	</div>
        	
        	<div class="card-body">
        		<?php echo $this->formCollection($this->form); ?>
        	</div>
        <?php echo $this->form()->closeTag($this->form); ?>
        </div>  
    </div>
    <div class="col-md-6">
    	<?php echo $this->partial('mapindex/partials/subtable.phtml', [
    	    'title' => 'Owners', 
    	    'data' => $this->owners, 
    	    'primary_key' => 'UUID',
    	    'route' => 'owners/default',
    	    'map_uuid' => $this->primary_key,
    	    'params' => [
    	        [
    	            'key' => 'UUID_O',
    	            'action' => 'update',
    	            'route' => 'owners/default',
    	            'label' => 'Update',
    	        ],
    	        [
    	            'key' => 'UUID',
    	            'action' => 'unassign',
    	            'route' => 'maps/default',
    	            'label' => 'Unassign',
    	        ],
    	    ],
    	]); ?>
    	
    	<?php echo $this->partial('mapindex/partials/subform.phtml', [
    	    'title' => 'Assign Owner', 
    	    'form' => $this->mapindex_assign_owner_form, 
    	]); ?>
    	
<!--     	<div class="card mb-4"> -->
<!--         	<div class="card-header d-flex justify-content-between"> -->
<!--         		<div> -->
<!--         			<b>Imagery</b> -->
<!--         		</div> -->
<!--         	</div> -->
        
<!--         	<div class="card-body"> -->
<!--        		<img src="http://MIMAS:8001/2018/map0001.tif" style="height: 200px; width: 200px;">   -->
<!--         	</div> -->
<!--     	</div> -->
    </div>
</div>