<div class="row">
	<div class="col-md-6">    
        <div class="card mb-4">
        <?php
        $this->form->prepare();
        echo $this->form()->openTag($form);
        ?>
        	<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Search</b>
        		</div>
        	</div>
        	
        	<div class="card-body">
        		<?php echo $this->formCollection($this->form); ?>
        	</div>
        <?php echo $this->form()->closeTag($this->form); ?>
        </div>  
    </div>
    <div class="col-md-6">
    	<?php echo $this->partial('mapindex/partials/subtable.phtml', [
    	    'title' => 'Owners', 
    	    'data' => $this->data, 
    	    'primary_key' => 'UUID',
    	    'params' => [
    	        [
    	            'key' => 'UUID',
    	            'action' => 'update',
    	            'route' => 'owners/default',
    	            'label' => 'Update',
    	        ],
    	    ],
    	]); ?>

    </div>
</div>